- pycheribuild/projects/build_qemu.py
QEMU now supports 128bit CHERI capabilities.
https://github.com/CTSRD-CHERI/qemu/commit/40a7fc2823e2356fa5ffe1ee1d672f1d5ec39a12
> Switch QEMU to real 128bit capabilities

- pycheribuild/projects/cheribsd.py
Add switch to use the CHERIxxx_PURECAP_MALTA64 conf files for building the kernel.
Currently these are only present in the cheribsd purecap-kernel branch.
> Add cheribsd/pure-cap-kernel switch

- pycheribuild/projects/cheribsd.py
Not sure whether we should also make sure that clang is called with -no-capsizefix.
> Let lld handle capability relocations when linking the kernel with lld.

- README.md
Currently README states that cheribuild.py builds the whole software stack for 256-bit CHERI by default. This behaviour was changed in 880bbe0.
While we're here, I'd like to update cheribuild.py usage output, fit it in 80 columns so that it doesn't require horizontal scroll on GitHub and use the tilde symbol instead of user-specific paths.
> Update cheribuild.py usage in README.

- pycheribuild/config/chericonfig.py
- pycheribuild/projects/cross/crosscompileproject.py
Useful for specifying the cable id when a system has multiple attached
FPGAs, for example: --benchmark-fpga-extra-args="-c 2"
> Add --benchmark-fpga-extra-args

- beri-fpga-bsd-boot.py
It is currently an argument to runbench but used in the boot_bsd()
function, which is called by bootonly as well as runbench.
Making it an argument to parser is the clean solution but will break existing scripts - perhaps it is better to add it as an argument to runbench, bootonly, and whatever other subcommands use it?
> beri-fpga-bsd-boot: make -k an argument to parser

- pycheribuild/filesystemutils.py
- pycheribuild/projects/go.py
- pycheribuild/projects/syzkaller.py
This adds build targets to build the mips64-enabled go compiler and runtime, and syzkaller.
> Add Golang and Syzkaller build targets

- pycheribuild/projects/llvm.py
Add libcxx, libcxxabi, compiler-rt, and libunwind to the llvm target.
This avoid the need to use the host equivalents, and works around the
fact that newish GCC's bits/regex.tcc names a variable "__output", which
we take to be a reserved word.
> llvm: use internal c++ goodies

- pycheribuild/projects/cross/cheribsd.py
Setting it to an invalid value breaks native builds and we'd already
commented out setting it elsewhere.
> Don't set XAS.

- pycheribuild/projects/cross/rtems.py
```
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5/
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//usr
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//usr/libcheri
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include/time.h
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include/semaphore.h
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include/pwd.h
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include/utime.h
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include/inttypes.h
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include/ssp
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include/ssp/stdlib.h
/Users/alex/cheri/output/sdk/riscv64-unknown-rtems5//include/ssp/unistd …
```
> Rtems fixes

- pycheribuild/projects/cross/nginx.py
The default config fails due to dlopen() failing...
> Don't force to static.

- pycheribuild/config/jenkinsconfig.py
- pycheribuild/config/target_info.py
- pycheribuild/projects/cross/compiler-rt.py
- pycheribuild/projects/cross/newlib.py
- pycheribuild/projects/cross/rtems.py
- pycheribuild/projects/project.py
This also installs rtems into $SDK/sysroot-rtems-riscv64-purecap.
Seems to work for me, but would be good if you could also check.
> Remove duplicated RTEMS target infos

- pycheribuild/projects/project.py
Don't perform any updates if the current branch doesn't have an upstream.  Also, avoid an attempt to update if our current revision is equal to that of the upstream branch.  Most usefully, that avoids a prompt to stash outstanding changes and update when there is no work to do.
> Avoid unnecessary updates

- pycheribuild/projects/project.py
This should avoid unnecessary rebuilds since `pull --rebase` might change
modification times of file.
I'm not sure if we need the `git rev-parse --abbrev-ref --symbolic-full-name @{upstream}` or whether `git fetch` will always do the right thing.
> Skip pull --rebase if the current branch is ahead of upstream

- pycheribuild/projects/cross/nginx.py
- pycheribuild/projects/cross/sqlite.py
Currently these are barely modified from the existing targets.  nginx needs to use the vulnerable openssl once we've created a target.
> Add a couple FETT build targets

- pycheribuild/__main__.py
- pycheribuild/boot_cheribsd/__init__.py
- pycheribuild/projects/cross/cheribsd.py
in addition to -DWITH_TESTS dtrace also requires -DWITH_DTRACE_TESTS.
Other than this, there are minor fixes to boot_and_login.
The question is: should the boot be stopped when there is a USER_CHERI_EXCEPTION?
if so, then the change in boot_cheribsd/__init__.py should be reverted
> Add -DWITH_DTRACE_TEST cmd line option

- pycheribuild/config/chericonfig.py
- pycheribuild/projects/build_qemu.py
- pycheribuild/projects/cherisim.py
- pycheribuild/projects/project.py
- pycheribuild/projects/run_fpga.py
This makes it easier to setup a dev environment outside the CL, with a local quartus install.
- Add option to use a custom environment setup script instead of the cheri-cpu ones. This is useful if   you are not running within the CL NFS or have different NFS mount-points.
- Always build the qemu SLIRP from git as it may complain when looking for the system one.
> Add options to use the local FPGA build environment.

- pycheribuild/config/target_info.py
- pycheribuild/projects/cross/compiler-rt.py
Otherwise it fails to find it in the build dir with this error:
llvm-config failed with status No such file or directory
> compiler-rt: Use self.sed_bindir to set LLVM_CONFIG_PATH

- pycheribuild/config/target_info.py
Function to populate `CMAKE_PREFIX_PATH` in `CrossToolchain.cmake` should include the subdirectory `libcheri/cmake` for `find_packages()` to find the right `Find[Project].cmake` file.
> point CMAKE_PREFIX_PATH to Find[PROJECT].cmake files

- pycheribuild/projects/cross/ros2.py
Creates a cheribuild target for a minimal subset of ROS2 c/cpp libraries and some examples.
> add target for ros2 libraries

- pycheribuild/projects/run_qemu.py
Otherwise we go to great lenghts to compute the correct path in
LaunchCheriOSQEMU.__init__ only to clobber it in LaunchQEMUBase.setup().
> cherios vs. run_qemu: override qemu binary in setup()

- pycheribuild/projects/cross/cheribsd.py
- pycheribuild/projects/project.py
This file is parsed by cheribuild to determine whether a clean build is
required. It will read the last non-empty, non-comment line as an integer and
compare that to the value read from this file at the last time.
The previous logic using timestamps was fragile and did not consider git
branches. Reading a file that is committed to the repository fixes this
issue:
I will commit the following file to CheriBSD once this change has landed:
```
20200526
```
> Allow forcing clean build using a .require_clean_build in the git repo

- README.md
- pycheribuild/projects/cross/cheribsd.py
- tests/test_argument_parsing.py
CheriBSD only supports 128-bit CHERI on MIPS and this is more inline
with RISC-V.
> Use CHERI_* configs for CheriBSD on MIPS.

- pycheribuild/projects/disk_image.py
Closes #112
Please test this on Linux/macOS; newfs claims that it needs to use tunefs for softupdates, I assume makefs is the same, and I don't know whether it'll work out of the box currently when bootstrapping.
> Use UFS2 for all rootfs images and enable soft updates journaling

- pycheribuild/projects/run_qemu.py
And report when we can't find either "ss" or "netstat" on Linux, and
report (rather than silently saying nothing) if we're on an unknown
platform.
@anaaktge reported some rather ugly spew from a system lacking `netstat`:
```
sh -c 'netstat -tulpne | grep ":10005"'
sh: 1: netstat: not found
Fatal error: Command `sh -c 'netstat -tulpne | grep ":10005"'` failed with non-zero exit code 1. Working directory was /home/a
```
As `ss` is the new hotness on Linux (part of the `iproute2` suite), hopefully this clears that up.
> run_qemu: look for "ss" on Linux when reporting port usage

- pycheribuild/projects/cross/cheribsd.py
GOOGLETEST takes many minutes to compile and link with an
assertions-enabled clang (some of the tests take 30 seconds to compile and
about 6 minutes to link). Since the only user of GOOGLETEST in CheriBSD is
capsicum-test, disable it by default.
It's marked as BROKEN_OPTIONS on MIPS so we weren't building it at all until
https://github.com/CTSRD-CHERI/cheribsd/pull/544 enabled C++ support for RISC-V.
> CheriBSD: Disable GOOGLETEST by default

- pycheribuild/projects/project.py
bash in particular does some truly egregiously strange things involving
"kill(0, SIGTTIN);" in `jobs.c:/^initialize_job_control` (shortly after
compensating for bugs arising from NeXT and Alliant systems...).
In any case, this logic interacts poorly with itself across time: if
multiple interactive shells run sequentially on the same tty, the first
one will successfully declare its PID the foreground process group for
its tty, but the second one will see that the earlier (now dead) task as
the foreground process group and will resist installing itself.
We can verify that this is what's going on with something like
sh <<HERE
ps -o pid,pgid,tty,tpgid,cmd \$\$
bash -i -c "ps -o pid,pgid,tty,tpgid,cmd \\$\\$"
bash -c "ps -o pid,pgid,tty,tpgid,cmd \$\$ \\$\\$"
HERE
which produces something like …
> Don't force shell scripts to be interactive

- pycheribuild/projects/sail.py
I still have to do a little bit of a dance to make it work, but it's much less exciting with these deltas in place.  Sail ends up installed as if via opam (i.e., in the opamroot, in the versioned switch that cheribuild creates).
```
git clone ... ott
git clone ... lem
git clone ... linksem
git clone ... sail
ln -s sail sailfromsource
./cheribuild/cheribuild.py sail-from-source
CHECK_IF_PREINSTALLED=false /usr/bin/opam install --root=/cheri/out/mainline/sdk/opamroot ocamlbuild
/usr/bin/opam install --root=/cheri/out/mainline/sdk/opamroot zarith menhir num base64 pprint yojson omd
./cheribuild/cheribuild.py ott
./cheribuild/cheribuild.py lem
./cheribuild/cheribuild.py linksem
./cheribuild/cheribuild.py sail-from-source
```
* Most of that dance would go away if cheribuild knew a little more …
> Changes for sail-from-source

- pycheribuild/config/chericonfig.py
- pycheribuild/config/defaultconfig.py
- pycheribuild/config/jenkinsconfig.py
- pycheribuild/config/target_info.py
- pycheribuild/projects/project.py
- tests/test_argument_parsing.py
The ABI is now only forced if --cap-table-abi is given explicitly.
While here, remove support for the legacy ABI.
> Don't force a default cap table ABI.

- pycheribuild/mtree.py
`file` is None in this case...
I've verified this fixes fett-config, but not checked the new symlink for /usr/lib*.
> Fix add_syslink when symlink_dest is specified.

- pycheribuild/boot_cheribsd/__init__.py
- pycheribuild/projects/cross/cheribsd.py
This is needed to account for purecap kernel slowness.
> Bump up cheribsd boot timeout for login prompt

- pycheribuild/projects/cross/freertos.py
The current ordering attempts to clean the app built in the previous iteration of the loop.  If the outer loop also iterates, then it's also trying to clean a program built for a different demo (RISC-V-Generic versus RISC-V_Galois_P1).
This doesn't become an obvious problem if you're only building apps in RISC-V-Generic that also exist for RISC-V_Galois_P1, because the app name is hardcoded in the Makefiles for both demos, therefore `make clean` happily runs, though it may be cleaning the wrong app:demo combination.
In my case, however, I added an app (`main_modbus`) only to the RISC-V-Generic demo.  It built `RISC-V-Generic:main_modbus`, then the outer loop iterated to RISC-V_Galois_P1.  Since PROG was still set to main_modbus, it then tried to clean `RISC-V_Galois_P1:main_modbus`, which …
> freertos:  run make clean on the demo/app combination about to be built

- pycheribuild/projects/cross/cheribsd.py
This only has an effect on the caprevoke branch as these make options
don't exist elsewhere.
> Enable DLMALLOC and CAPREVOKE for cheribsd-fett.

- pycheribuild/config/compilation_targets.py
- pycheribuild/config/defaultconfig.py
- pycheribuild/config/jenkinsconfig.py
- tests/setup_mock_chericonfig.py
cheribuild currently installs the sysroots under the sdk dir, which is derived
from the tools_root, which, in turn, defaults to the output_dir.  When
attempting to share tools directories between long-lived branches of cheribsd
(for example), this derivation chain implies that the sysroots end up in the
nominally shared tools directory, which is not desirable.  This change allows
cheribuild to still use a shared compiler and qemu (and so on) and yet use
different sysroots.
> Add --sysroot-install-dir configuration option

- docker/Dockerfile
- pycheribuild/__main__.py
- pycheribuild/projects/cross/cheribsd.py
Fix a number of issues that prevented running cheribuild in the docker configuration. I'm new to this, so hopefully these are all reasonable fixes!
- Install missing samba dependency in Dockerfile
- Install missing texinfo dependency in Dockerfile (required for building GDB)
- Don't attempt to remove schg flag on non-BSD systems, the chflags command doesn't exist on Linux
> Various fixes for docker build

- pycheribuild/config/chericonfig.py
- pycheribuild/config/compilation_targets.py
- pycheribuild/config/defaultconfig.py
- pycheribuild/config/jenkinsconfig.py
- pycheribuild/projects/cross/cheribsd.py
- pycheribuild/projects/llvm.py
- pycheribuild/projects/project.py
- pycheribuild/projects/run_qemu.py
- pycheribuild/qemu_utils.py
- tests/setup_mock_chericonfig.py
Not 100% sure I got the compiler flags and make options for CheriBSD right.
I have the following in my cheribuild.json to find the right repositories:
```json
"morello-sdk-root": "$MORELLO_ROOT/output/morello-sdk",
"morello-llvm": {
"source-directory": "$MORELLO_ROOT/git/morello-llvm-project/",
"build-directory": "$MORELLO_ROOT/build/morello-llvm-project-build/"
},
"cheribsd-morello-hybrid": {
"source-directory": "$MORELLO_ROOT/git/morello-cheribsd/",
"build-directory": "$MORELLO_ROOT/build/cheribsd-morello-hybrid-build/",
"install-directory": "$MORELLO_ROOT/output/rootfs-morello-hybrid/"
},
"cheribsd-morello-purecap": {
"source-directory": "$MORELLO_ROOT/git/morello-cheribsd/",
"build-directory": "$MORELLO_ROOT/build/cheribsd-morello-purecap-build/",
"install-directory": …
```
> Initial Morello support

- README.md
We are building CHERI on Fedora distro, as part of EPSRC-funded Capable VMs project. 
We listed the Fedora dnf packages that need to be installed to build CHERI.
> Specify build dependencies for Fedora dnf package manager

- pycheribuild/config/compilation_targets.py
- pycheribuild/config/target_info.py
- pycheribuild/projects/cross/cheribsd.py
This is motivated by perl, where I want to include the FreeBSD TARGET_ARCH in its targetarch variable that gets printed in perl --version (and used in some directory names).
> Move TARGET_ARCH computation to common code

- pycheribuild/projects/cross/gdb.py
After 6edd51bc7326 (FreeBSD) / 6c4dac25e39d (CheriBSD), liblzma depends on
libmd, but this isn't automagically picked up by configure, so hold the build
system's hand.
> gdb: add -lmd when compiling for target

- pycheribuild/__main__.py
Builds have now been done against a variety of targets including riscv64-hybrid, riscv64-purecap and morello.  All of them succeeded on Big Sur (11.1) and the system did not require a reboot.,
> With recent changes by arichardson we can now build on Big Sur (11.1)

- pycheribuild/files/minimal-image/boot.files
- pycheribuild/projects/cross/cheribsd.py
- pycheribuild/projects/disk_image.py
- pycheribuild/projects/run_fvp.py
- pycheribuild/projects/run_qemu.py
- tests/test_argument_parsing.py
- tests/test_target_order.py
Currently we regard minimal images as being the images embedded MFS_ROOT kernels, but they have another use case as just being a much smaller disk image. This separates things out everywhere so both exist, with minimal images now being bootable, and MFS_ROOT images only being a rootfs.
> Deconflate minimal and MFS_ROOT images

- pycheribuild/config/defaultconfig.py
tools_root defaults to output_root, so this should induce no changes for people
not setting tools_root explicitly.
> Find default_morello_sdk in tools_root, not output

- pycheribuild/config/compilation_targets.py
- pycheribuild/projects/project.py
Without this change I get the following after killing QEMU inside the
test script:
[1]+  Stopped                 cheribuild.py cmake-riscv64 --test --interact-after-tests
alex@Alexs-MBP-10:~/devel/cheribuild(master * u=)> fg
cheribuild.py cmake-riscv64 --test --interact-after-tests
Warning: '/Users/alex/devel/cheribuild/test-scripts/run_simple_tests.py --ssh-key /Users/alex/.ssh/id_ed25519.pub --architecture riscv64 --kernel /Users/alex/cheri/output/kernel-riscv64.QEMU-MFS-ROOT --qemu-cmd /Users/alex/cheri/output/sdk/bin/qemu-system-riscv64cheri --build-dir /Users/alex/cheri/build/cmake-crosscompiled-riscv64-build --source-dir /Users/alex/cheri/cmake --sysroot-dir /Users/alex/cheri/output/rootfs-riscv64 --interact --test-command 'cd /build/bin && ./ctest --help' --test-timeout 7200' error …
> Fix --test causing cheribuild to be suspended

- pycheribuild/config/chericonfig.py
- pycheribuild/config/compilation_targets.py
- pycheribuild/projects/cross/bbl.py
- pycheribuild/projects/cross/cheribsd.py
- pycheribuild/projects/project.py
- pycheribuild/projects/run_fpga.py
- pycheribuild/projects/run_qemu.py
- pycheribuild/projects/spike.py
- pycheribuild/projects/syzkaller.py
- tests/test_argument_parsing.py
This attempts to have a separate class to fetch (and possibly generate) kernel configuration variants to build and run in cheribuild targets.
> Try to cleanup the handling of cheribsd kernel configuration files

- Jenkinsfile
- README.md
- pycheribuild/utils.py
- tests/python-390.Dockerfile
- tests/run_jenkins_tests.sh
- tests/ubuntu.Dockerfile
Ubuntu 16.04 has been EOL for a while and based on the python versions
available on most Linux distributions requiring 3.6 seems like a
reasonable baseline. While I would like to use 3.7 for dataclasses,
Ubuntu 18.04 ships 3.6 and that's probably the distribution that is most
commonly used when building CHERI projects.
Bumping the Python version to 3.6 allows using features such as f-strings
and type annotations on variables (https://docs.python.org/3/whatsnew/3.6.html).
> Drop support for Ubuntu 16.04 and Python < 3.6

- pycheribuild/config/chericonfig.py
- pycheribuild/projects/project.py
- tests/test_argument_parsing.py
When building e.g. KDE programs, I want to build the KDE framework
dependencies but skip targets that take a long time to build such as QtBase
and all the underlying dependencies. This patch lets me do the following:
`cheribuild.py <target> -d --skip-sdk "--skip-dependency-filter=qt.*" "--skip-dependency-filter=libx.*"`
This avoids lots of build time (especially when combined with --clean or
--reconfigure since we also need to build a native qtbase+qtdeclarative
for the bootstrap tools in KConfig and other frameworks.
> Add the ability to filter the built dependencies with regexes

- pycheribuild/projects/disk_image.py
> Use FAT-32 for EFI filesystem images made via makefs.

- README.md
- pycheribuild/projects/build_qemu.py
Rather than just letting configure happen to find it, cause it to bail if it
can't.  Add the requisite packages to README.md, while here.
> build_qemu: ensure zstd support

- pycheribuild/processutils.py
- pycheribuild/projects/cross/x11.py
Some binaries (e.g. xkbcomp) can't find the required libraries otherwise.
Dealing with the multiple levels of quoting in autotools projects is
rather awkward and it took me a while to find something that works:
`'$$ORIGIN/../lib'` (in single quotes).
> Rather awful approach to add a $ORIGIN RUNPATH to X11 libs

- docker/Dockerfile
Works for me when built locally with: `docker build -t ctsrd/cheribuild-docker:latest cheri/cheribuild/docker`
> Add telnet to the docker image for the FVP

- pycheribuild/projects/cross/neomutt.py
This adds basic support for building the Neomutt email client.  Some nice-to-have functionality is not enabled (header caches, SASL, NLS, international domain names) but as-is it's basically usable for talking to IMAP/SMTP servers.
Tested with Fastmail with the following config flags to avoid SASL:
```
set smtp_authenticators="login"
set ssl_starttls = yes
set ssl_force_tls = yes
```
> Add a recipe for Neomutt command line email client

- pycheribuild/projects/run_qemu.py
The eventual plan is combine the CheriOS nanokernel with any firmware
required for a particular platform. As it stands, CheriOS will only run
with this flag.
> Pass -bios none for CheriOS QEMU

- pycheribuild/projects/cross/cheribsd.py
When using --subdir, we should execute install and installconfig tragets to install optional configuration.
Note that installconfig doesn't fail if there is no configuration in a subdirectory.
> Install optional configuration with --subdir.

- open-morello-serial-ports.py
It supports two modes of operation:
- When invoked with --tmux, the script creates a new tmux session with
all 8 UARTs connected using four panes in two tmux windows.
- When invoked with --uart <index|name>, it launches picocom attached
to that specific UART.
Only tested on macOS so far, but should hopefully work on Linux/FreeBSD/WSL.
> Add a script to connect to the Morello board UARTs

- pycheribuild/projects/disk_image.py
With the previous settings, we could install the llvm package, but
we'd have negative free space and even with things like deleting the
package cache don't have enough space to add GDB.  Empty space is cheap
so just double to 2g.
> Give large disk images even more free space

- pycheribuild/projects/cross/openssh.py
With older openssh versions (e.g., the one used in FETT) DESTDIR
could be passed in the environment.  In the current openssh-portable
build system, it must be passed as an argument to override it being
set to the empty string in Makefile.
> openssh: Pass DESTDIR as an argument

- pycheribuild/projects/cross/cheribsd.py
- Add Morello benchmark (`NODEBUG`) kernels
- Bring caprevoke kernel configs up to date with the latest merge
> Update CheriBSD kernel configurations

- pycheribuild/projects/cross/openssh.py
Set configure and make arguments in setup so they are alwasy set and
make configure() only handle autoreconf.
Fixes:		#297
Suggested by:	@jrtc27
> Fix DESTDIR passing for openssh

- README.md
CheriBSD cross-build has come to depend on a `time` executable in the
host $PATH, but Ubuntu 22.04, at least, doesn't consider that a
worthwhile thing to have installed by default.
> README: add time package for Debian/Ubuntu systems

- pycheribuild/projects/cross/cheribsd.py
Can be disabled by building with --cheribsd/build-type=Debug
> CheriBSD: Default to enabling MALLOC_PRODUCTION

- pycheribuild/projects/cross/gdb.py
- tests/test_argument_parsing.py
- tests/test_target_order.py
- The rule to add "gmp" in dependencies() was inverted.
- The check for "gmp" in dependencies later also did not work as it would not match on dependencies like "gmp-riscv64-purecap-for-rootfs".  However, we can just make this unconditional now.
- Use --with-gmp and --with-libgmp-prefix variables rather than directly setting CFLAGS and LDFLAGS.  Note that GDB master (soon to be 13) follows binutils in using --with-gmp only for this.
- Change the default branch to cheri-12 across all architectures removing logic for morello-specific branches.
> Update CHERI GDB to the cheri-12 branch.

- pycheribuild/projects/cross/libcxx.py
This currently requires changes cherry-picked to the dev branch of llvm, so can only be merged once those land in master.
> Use the LLVM runtimes build for llvm-libs

- pycheribuild/projects/build_qemu.py
Previously, building without the source directory would fail.
This is the same solution used for samba: https://github.com/CTSRD-CHERI/cheribuild/blob/9b7f601aae30cd0d6ae2e51436b168c9a5c78fa9/pycheribuild/projects/samba.py#L95
> build_qemu: move check for commit to `configure` to ensure the repository is cloned

- pycheribuild/utils.py
Here's an example of the os-release file for CentOS 7:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
The blank line broke the previous parser.
The man page for os-release (`OS-RELEASE(5)`) specifies:
> Lines beginning with "#" are treated as comments. Blank lines are
> permitted and ignored.
This modified parser will still fail if a line doesn't contain '=', I beleive this is acceptable since OS-RELEASE(5) specifies that each line should be …
> utils: ignore blank lines and comments in os-release file

- README.md
inetutils is required for the hostname command, without which CheriBSD
build fails on my machine.
> add inetutils to arch deps

- pycheribuild/projects/cross/juliet_test_suite.py
- test-scripts/run_juliet_tests.py
- Add the following CWE entries in addition to already present in `juliet_test_suite` project of `cheribuild`
- 122 Heap-based Buffer Overflow
- 124 Buffer Underwrite ('Buffer Underflow')
- 127 Buffer Under-read
- 134 Uncontrolled Format String
- 188 Reliance on Data/Memory Layout
- 587 Assignment of a Fixed Address to a Pointer
- 588 Attempt to Access Child of a Non-structure Pointer
- 685 Function Call With Incorrect Number of Arguments
- 843 Access of Resource Using Incompatible Type ('Type
Confusion')
- Treat compiler detected bugs as warnings, not errors, for relevant CWE entries.
- Provide user input from stdtin, files and environment that triggers illegal memory access.
> Add more CHERI-relevant tests from Juliet test suite

- pycheribuild/projects/cross/cheribsd.py
Take 2 for appeasing `caprevoke` CI
> cheribsd: yet more caprevoke kernels (MFS)

- pycheribuild/projects/cross/cheri_exercises.py
Now that the symbols are defined in the release images, it's probably fine to kick compiling these on by default, even if they won't run on a non-Cornucopia release.
> cheri-exercises: also build heap revocation exs.

- pycheribuild/projects/cross/gdb.py
- pycheribuild/projects/cross/gmp.py
On a fresh installation of FreeBSD, the GDB build will fail in configure when it can't find makeinfo.  This is part of the texinfo package.
> GDB: register dependency on texinfo

- pycheribuild/files/cheribsd/rc.conf.in
- pycheribuild/projects/cross/cheribsd.py
- pycheribuild/projects/disk_image.py
We're unlikely to need to run this again so remove the clutter.
> Remove support for the BESSPIN evaluation tool

- pycheribuild/files/cheribsd/fstab.in
- pycheribuild/projects/disk_image.py
Add support for simple ZFS images.  The images contain a single 5GiB pool (zroot) mounted at /.  They can be created with the disk-image-zfs target and can be booted in qemu with the run-zfs target.
This has been tested on morello-purecap and amd64. The results should work on any platform that uses the FreeBSD loader as kernels don't typically contain the ZFS module. This means it will not work on RISC-V unless the kernel configuration is altered to build ZFS in.
This depends on https://github.com/CTSRD-CHERI/cheribsd/pull/1620
> Support ZFS images for CheriBSD

- pycheribuild/projects/simple_project.py
pkg-config --exists also checks dependencies are present on macOS, and due to some packaging issues with upstream libarchive this is breaking the build for cheribsd and freebsd.
Closes #340.
See https://github.com/Homebrew/homebrew-core/issues/120526 for tracking of this issue as it relates to macOS.
> Use --modversion instead of --exists to check library is installed

- README.md
I've added expat and gmp to the package lists for Debian and Arch. I needed these to build the riscv64 SDK.
expat is already included in Fedora, but not gmp? Perhaps it's a dependency of something else already or should it be added?
> Add expat and gmp Debian and Arch package lists

- pycheribuild/projects/cross/cheribsd.py
If you have a build option such as `OPTION=\"-DFOO=BAR\"` then the parsing of the config file fails. This just splits the string on the first `=` so the full value (with the second `=`) remains unchanged
> split on only the first `=` when parsing build options

- pycheribuild/config/defaultconfig.py
- pycheribuild/utils.py
If we're heavily firewalled, the attempt to check whether we're online doesn't really indicate whether or not we'll be able to reach, for example, github.com .  Operating in such an environment, I have historically just stubbed out the test locally, but rather than continuing to do that, having an option could be nice.
> Add --presume-connectivity option

- pycheribuild/projects/run_fvp.py
When reading a trace file from a live model, it's usually important that the trace file is unbuffered. This is particularly useful in combination with ToggleMTIPlugin.
> Add --run-fvp/trace-unbuffered.

- pycheribuild/projects/build_qemu.py
enable-plugins config option for cheribuild qemu target, allows qemu to use dynamically loaded plugins (good for profiling, instruction counting, etc). This links with pull request https://github.com/CTSRD-CHERI/qemu/pull/215
> add enable-plugins option for QEMU build config

- pycheribuild/config/compilation_targets.py
- pycheribuild/projects/build_qemu.py
- pycheribuild/projects/cross/bbl.py
- pycheribuild/projects/cross/compiler_rt.py
- pycheribuild/projects/cross/device_model.py
- pycheribuild/projects/cross/littlekernel.py
- pycheribuild/projects/cross/opensbi.py
- pycheribuild/projects/cross/u_boot.py
- pycheribuild/projects/fvp_firmware.py
- pycheribuild/projects/run_qemu.py
- pycheribuild/projects/spike.py
- tests/test_target_order.py
Currently BBL and other freestanding baremetal targets use the newlib target info but that is not quite right - introduce a new one that does not include a libc. No functional change intended.
> Introduce a freestanding target info

- pycheribuild/config/config_loader_base.py
- pycheribuild/projects/cross/cheribsd.py
- tests/test_argument_parsing.py
When the kernel-config is specified explicitly, extra kernels should not be built.
> cheribsd: Ensure that the kernel-config override only builds one kernel.

- pycheribuild/boot_cheribsd/__init__.py
- pycheribuild/projects/cross/benchmarks.py
- pycheribuild/projects/cross/libcxx.py
- pycheribuild/projects/repository.py
- test-scripts/run_libcxx_tests.py
TL;DR: We haven't been testing the Morello purecap kernel in CI since the end of December as the tests are booting the hybrid kernel instead.
> Morello purecap kernel

- README.md
I added "texinfo" and "mercurial" to the packages that need to be installed on macOS with Homebrew. I needed to install these in addition to packages that are already listed in the readme file to build the "run-riscv64-purecap" target.
> Added missing macOS dependencies

- pycheribuild/projects/cross/cheribsd.py
- tests/test_argument_parsing.py
CheriBSD now includes revocation by default so invert the --cheribsd/caprevoke-kernel support in favor of a slightly awkward --cheribsd/nocaprevoke-kernel option which enables -NOCAPREVOKE kernels.
Addresses #377
> caprevoke-kernel -> build-nocaprevoke-kernel

- pycheribuild/config/compilation_targets.py
- pycheribuild/config/loader.py
- pycheribuild/processutils.py
- pycheribuild/projects/cherios.py
- pycheribuild/projects/cross/benchmark_mixin.py
- pycheribuild/projects/cross/cheribsd.py
- pycheribuild/projects/cross/llvm.py
- pycheribuild/projects/meson_project.py
- pycheribuild/projects/repository.py
- pycheribuild/projects/run_qemu.py
- pycheribuild/projects/simple_project.py
Avoid cyclic (deferred) imports and use a string target name lookup instead of ProjectCls.get_instance().
The main benefit here is that it allows pytype to run more checks in parallel. It may also result in a very minor speedup.
PR for CI checks.
> Speed up pytype by removing imports

- pycheribuild/projects/disk_image.py
Hi, I noticed that the file permission of `/etc/pam.d/system` is incorrect when I was using the minimal disk image. It prompts that:
```
2024-01-28T07:59:02.046161+00:00 - login 83 - - in openpam_check_desc_owner_perms(): /etc/pam.d/system: insecure ownership or permissions
2024-01-28T07:59:02.059751+00:00 - login 83 - - pam_start(): System error
```
And if I log out the system, I can never log in back.
This PR tries to fix this issue by ensuring the file permission of `/etc/pam.d/system` to be `0644` when building the rootfs. After applying this patch, I can log out and log in again without any issue.
```
Logging in as root...
2024-01-28T09:27:25.194438+00:00 - login 83 - - login on console as root
exec /bin/sh
CheriBSD/arm64 (Amnesiac) (ttyu0)
login: root …
```
> ensure 0644 perms for `/etc/pam.d/system`

- pycheribuild/config/target_info.py
- pycheribuild/projects/cmake_project.py
- pycheribuild/projects/simple_project.py
morello-llvm-native on CheriBSD/Morello requires -mabi=aapcs in CFLAGS. Otherwise, it would be compiled with -mabi=purecap that cc uses by default on CheriBSD with purecap world.
> Pass compiler/linker flags to CMake for -native-hybrid

- tests/test_argument_parsing.py
A bit of reformatting to simplify later diffs plus pacifying newer ruff versions.
> Test tidying

- .github/workflows/python-app.yml
- tests/requirements.txt
- tests/run_basic_tests.sh
- tests/test_argument_parsing.py
Similar to https://github.com/CTSRD-CHERI/cheribuild/pull/395
but centralizing it in requirements.txt
> GitHub Actions: Pin ruff to the same version as pre-commit

- pycheribuild/projects/cross/cheribsd.py
- tests/test_argument_parsing.py
Switch the default kernel ABI to purecap
> Default to purecap kernels for CheriBSD

- pycheribuild/projects/cross/cheribsd.py
- tests/test_argument_parsing.py
This reverts commit de423d149a976a5118d88d879a4a64ae0487400d.
> Revert "Default to purecap kernels for CheriBSD"

- pycheribuild/projects/cross/freertos.py
Depends on https://github.com/CTSRD-CHERI/FreeRTOS-Demos-CHERI-RISC-V/pull/5, and requires the hmka2 branch of https://github.com/CTSRD-CHERI/FreeRTOS to bump the Demos submodule to include it.
> Add --implicit-mem-0 option to FreeRTOS demos to disable zero-init

- pycheribuild/projects/cross/cheribsd.py
- tests/test_argument_parsing.py
This is inhibited by the no-build-alternate-abi-kernels.
> Build Morello benchmark ABI kernels.

- pycheribuild/projects/cross/python.py
Single line change that fixes cross-compilation of Python.
> Add --with-build-python to Python cross-compilation configuration

- README.md
I found on Fedora 40 (qubes) that the only time executable was the shell builtin, which caused a rather cryptic error for cheribuild, complaining "MAKEOBJDIRPREFIX" is not set, cannot continue! "  Installing the package fixed it and the build worked without a hitch.
> Add time to fedora package list

- pycheribuild/projects/bluespec_compiler.py
'bluespec-libraries' builds and installs the B-lang-org/bsc-contrib repo into the local install.
'bluespec' is a dummy target which depends on 'bluespec-libraries' which depends on 'bluespec-compiler', so building 'bluespec' with dependencies builds both.
Upstream bluespec-compiler's makefile tends to rebuild all its BSV files even if nothing changed, so building 'bluespec-libraries' also causes the BSV inside bluespec-compiler to get rebuilt.  Not sure if there's an easy solution for this.
> Add build for B-lang-org/bsc-contrib repo as 'bluespec-libraries' target, also add 'bluespec' alias

- pycheribuild/projects/cross/gmake.py
Without this, the build dies with
```
cd /cheri/source/mainline/gmake && /cheri/source/mainline/gmake/autogen.sh
/cheri/source/mainline/gmake/autogen.sh: 1088: cannot open gnulib/gnulib-tool: No such file
Fatal error (in target gmake-aarch64): Command `/cheri/source/mainline/gmake/autogen.sh` failed with non-zero exit code 2. Working directory was /cheri/source/mainline/gmake
```
> gmake: bootstrap to fetch gnulib before configuring

- pycheribuild/projects/cross/cheribsd.py
llvm-link is used by the kernel-c18n branch to generate an IR file of the kernel.
A corresponding change making use of this is in https://github.com/CTSRD-CHERI/cheribsd/commit/ae7327c781363ae6885e9716971c3052716197a6.
> cheribsd: use llvm-link from the SDK

- pycheribuild/projects/disk_image.py
This is required by libcrypt.so.5 after CheriBSD commit 4ca6f578846d947386821de5e740062c83f8376a.
> Add libmd.so.7 to minimal CheriBSD images

- pycheribuild/config/chericonfig.py
- pycheribuild/config/compilation_targets.py
- pycheribuild/config/target_info.py
- pycheribuild/projects/cross/cheribsd.py
- pycheribuild/projects/cross/llvm_test_suite.py
- pycheribuild/projects/disk_image.py
- pycheribuild/projects/project.py
- pycheribuild/projects/run_fvp.py
- pycheribuild/projects/testrig.py
- pycheribuild/utils.py
- pyproject.toml
All older versions are EOL and none of the distributions we support
should have such an old version.
> Require python 3.8

- pycheribuild/projects/cross/cheribsd.py
I believe this will fix the last CI failure in https://github.com/CTSRD-CHERI/cheribsd/pull/2309
> Remove an obsolete hack from the cheribsd buildworld target

- pycheribuild/boot_cheribsd/__init__.py
- pycheribuild/projects/build_qemu.py
- pycheribuild/projects/run_qemu.py
- pycheribuild/qemu_utils.py
See https://github.com/CTSRD-CHERI/qemu/pull/272
> Support suffixed RISC-V qemu binaries

- pycheribuild/projects/cross/newlib.py
The command `./cheribuild.py newlib-baremetal-riscv64-purecap -d` currently fails when using clang-15.
This issue has been reported multiple times on the Cheri Slack channel. 
As a workaround, this commit adds the `-Wno-implicit-function-declaration` option to suppress these errors. While this may not be a permanent fix, it should unblock users and help others facing the same problem.
> Work around newlib compilation failure with clang-15 

- pycheribuild/projects/disk_image.py
Add any files in usr/share/examples/cheribsdtest to that builds without purecap successfully add all zero of them rather than failing to add usr/share/examples/cheribsdtest/run-many.
This is breaking CI for CheriBSD.
> disk-image-minimal: use a glob for run-many

- pycheribuild/config/compilation_targets.py
NewlibBaremetalTargetInfo targets should add the target triple to the sysroot, as this was the layout expected by Newlib’s multilib install layout (and GCC's sysroot). The current MorelloBaremetal targets shouldn't assume a Newlib/GCC sysroot and should follow the FreeStanding target one. If there's a need for GCC's sysroot and multilib layout, this should go to a new NewlibMorelloBaremetalTargetInfo or something.
> Morello/baremetal: match Freestanding's sysroot dir

- pycheribuild/projects/build_qemu.py
Always build QEMU for hybrid. We don't support purecap yet.
This fixes building QEMU natively on CheriBSD/Morello.
> qemu: always build hybrid
