pycheribuild/projects/cheribsd.py
Change compiler flags for the kernel build with the external clang toolchain
Forward external toolchain args to the freebsd install targets
=> External toolchain

pycheribuild/projects/disk_image.py, pycheribuild/projects/elftoolchain.py
Mostly to elftoolchain build.  I found it necessary to run "make obj" on my FreeBSD VM, for example.  The rest are mostly superficial.
=> A few small changes

beri-fpga-bsd-boot.py
=> beri-fpga-bsd-boot: on panic, type "bt" at the debug prompt

README.md
Hello @arichardson,
Hope you are doing well. Have just updated the Readme.md for mentioning the packages to be installed for building Cheri on Ubuntu/ Debian box.
Let me know if any changes are required.
Kind Regards,
Vijay
=> Updated Readme.md mentioning the packages to install for building Cheri

pycheribuild/projects/cross/eigen.py
[Eigen's website](http://eigen.tuxfamily.org/index.php?title=Main_Page)
=> Add target for Eigen linear algebra libraries

pycheribuild/projects/cross/poco.py
Doesn't build successfully yet.
=> add target for poco c++ lib

pycheribuild/config/target_info.py, pycheribuild/projects/cross/cheribsd.py, pycheribuild/projects/cross/crosscompileproject.py, pycheribuild/projects/cross/nginx.py, pycheribuild/projects/cross/openssh.py, pycheribuild/projects/cross/openssl.py, pycheribuild/projects/cross/zlib.py, tests/test_argument_parsing.py
=> FETT OpenSSH and nginx linkage

pycheribuild/config/loader.py
Fixes #76, but unsure if a stylistically acceptable approach.
=> Abort on missing explicitly-given config file

pycheribuild/boot_cheribsd/__init__.py
This will hopefully fix some issue in Jenkins, where tests sometimes don't run cause of this command
=> Try several times to mount smbfs, with a higher delay between each trial

pycheribuild/boot_cheribsd/__init__.py
I Was trying to execute the second run inside the except
=> Fix issue in smbfs trials

pycheribuild/projects/cross/ros2.py
Building ROS creates a `setup.bash` file that should be `source`ed before running any ROS applications.  The `setup.bash` file sets environment variables (primarily `LD_LIBRARY_PATH`).
This PR creates an analogous file (`cheri_setup.csh`) after building ROS.  This file is created in `self.sourceDir` and should be `source`ed to set CHERI environment variables in CheriBSD (primarily `LD_CHERI_LIBRARY_PATH`) before running a ROS application.
=> create a setup file to set cheri env vars after install

pycheribuild/projects/cross/cheribsd.py
The other didn't seem to stick and this seems to be more the right mechanism.
=> Set WITH_CHERI in the CheriBSD build process.

beri-fpga-bsd-boot.py, pycheribuild/projects/cross/ros2.py, test-scripts/run_ros2_tests.py
First stab at adding testing for the ROS2 target.
This doesn't currently work.  If I don't load sysroot, the linker can't find `librt.so.1`.  If I do load sysroot, it can't find any of my libraries, even when LD_CHERI_LIBRARY_PATH appears to be set correctly.
=> ROS2 testing

pycheribuild/config/compilation_targets.py, pycheribuild/config/target_info.py, pycheribuild/projects/cross/cheribsd.py, pycheribuild/projects/cross/crosscompileproject.py, pycheribuild/projects/cross/fett.py, pycheribuild/projects/cross/kcgi.py, pycheribuild/projects/cross/nginx.py, pycheribuild/projects/cross/openssh.py, pycheribuild/projects/cross/openssl.py, pycheribuild/projects/cross/sqlbox.py, pycheribuild/projects/cross/sqlite.py, pycheribuild/projects/cross/zlib.py, pycheribuild/projects/project.py, pycheribuild/utils.py
=> Add support for automatic variable initialization

pycheribuild/boot_cheribsd/__init__.py, pycheribuild/utils.py
QEMU crashing or not shutting down properly because it was manually killed
can result in the current terminal behaving very strangely. To avoid this
problem, save the tcgetattr result and F_FLAGS values for stdin/stdout/stderr
before executing other processes and restore them again after.
With this change I get the following output if I kill -9 QEMU after this patch:
```
Previous state [25862, 5, 191, 2619, 15, 15, [b'\x03', b'\x1c', b'\x7f', b'\x15', b'\x04', b'\x00', b'\x01', b'\x00', b'\x11', b'\x13', b'\x1a', b'\x00', b'\x12', b'\x0f', b'\x17', b'\x16', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00']]
New state [24580, 5, 191, 2608, 15, 15, [b'\x03', b'\x1c', b'\x7f', b'\x15', b'\x04', 0, …
```
=> Restore TTY and file descriptor flags after running processes

pycheribuild/projects/cross/fett.py
=> FETT voting update

.gitignore
=> adds __pycache__ to gitignore

pycheribuild/projects/cross/gdb.py
This fixes building sim/ppc/igen
=> gdb: also pass -fcommon in CFLAGS_FOR_BUILD

pycheribuild/projects/cross/benchmarks.py
Add UnixBench, LMBench and NetPerf targets
=> Add more benchmarks targets

pycheribuild/projects/cross/cheribsd.py
Inherit the purecap_kernel option from the cheribsd kernel target instead
of requiring a new flag to be passed.
=> Properly inherit the purecap_kernel option for MFS root target.

pycheribuild/projects/cross/cheribsd.py
I still don't have a kernel that links yet, but I've been using this to do the builds so far.
=> Riscv purecap kernel

pycheribuild/boot_cheribsd/__init__.py, pycheribuild/config/compilation_targets.py, pycheribuild/projects/cross/benchmarks.py, pycheribuild/projects/disk_image.py, test-scripts/run_libunwind_tests.py
Depends on https://github.com/CTSRD-CHERI/cheribsd/pull/548
=> Unconditional libcheri

pycheribuild/projects/cross/benchmarks.py
=> Switch benchmark directories to CTSRD project.

pycheribuild/projects/cross/cheribsd.py
While here, move a comment about the malo module failure to the right
place.
=> Allow compiling kernel modules on RISC-V.

pycheribuild/config/compilation_targets.py, pycheribuild/projects/llvm.py
Add prefixed clang symlinks with config files for CheriBSD RISC-V
This adds cheribsd-rv64-hybrid-clang{,++,-cpp} symlinks that will have the
right --sysroot=, etc flags by default. This also renames the MIPS ones to
use cheribsd-mips-{hybrid,purecap} as a prefix since apparently recent
versions of clang also allow for dashes in config file name.
```
$CHERI_SDK/bin/cheribsd-rv64-purecap-clang /tmp/helloworld.c -o hello -v && $CHERI_SDK/bin/readelf -h hello
clang version 11.0.0
Target: riscv64-unknown-freebsd13
Thread model: posix
InstalledDir: /Users/alex/cheri/output/sdk/bin
Configuration file: /Users/alex/cheri/output/sdk/bin/cheribsd-rv64-purecap.cfg
"/Users/alex/cheri/output/sdk/bin/clang-11" -cc1 -triple riscv64-unknown-freebsd13 -emit-obj -mrelax-all -disable-free -main-file-name …
```
=> Add prefixed clang symlinks with config files for CheriBSD RISC-V

pycheribuild/projects/cross/cheribsd.py
Prevent appending duplicate -NODEBUG.
=> Fix generation of purecap kernel MFS root kernel config.

pycheribuild/config/chericonfig.py, pycheribuild/config/compilation_targets.py, pycheribuild/config/target_info.py, pycheribuild/filesystemutils.py, pycheribuild/mtree.py, pycheribuild/projects/cross/cheribsd.py, pycheribuild/projects/cross/crosscompileproject.py, pycheribuild/projects/cross/gdb.py, pycheribuild/projects/disk_image.py, pycheribuild/projects/fvp_firmware.py, pycheribuild/projects/llvm.py, pycheribuild/projects/project.py, pycheribuild/projects/run_fvp.py, pycheribuild/utils.py
=> Firmware fun

pycheribuild/boot_cheribsd/__init__.py, pycheribuild/config/jenkinsconfig.py, pycheribuild/jenkins.py, pycheribuild/projects/cross/benchmarks.py, pycheribuild/projects/cross/cheribsd.py, pycheribuild/projects/effectivesan.py, release-scripts/create_morello_release_tarball.py
We will also need to update the cheribsd dev Jenkinsfile.
=> Fix sysroot archive creation

pycheribuild/projects/cross/benchmarks.py
Is there a better way to do this?
=> spec2006-new: force u+w perms after unpacking

README.md
Just to remove those ugly syntax errors
=> Use jsonc to support comment

pycheribuild/projects/run_fvp.py, pycheribuild/projects/run_qemu.py
A quick-and-dirty approach to https://github.com/CTSRD-CHERI/cheribuild/issues/123 .
=> Add "extra-tcp-forwarding" options to QEMU and Morello FVP

pycheribuild/projects/build_qemu.py
Originally from @LawrenceEsswood
=> Add option to build qemu with profiler enabled.

pycheribuild/projects/cross/cheribsd.py, tests/test_argument_parsing.py
Also add a new platform specifically for AWS FPGAs.
=> Add AWS F1 purecap kernel configurations.

pycheribuild/boot_cheribsd/__init__.py
This removes the need to build the disk image without autoboot.
=> Interrupt autoboot for running tests on alternate kernel configurations.

pycheribuild/projects/cross/compiler-rt.py, pycheribuild/projects/project.py
Depends on https://github.com/CTSRD-CHERI/llvm-project/pull/532
This reverts commit 818377729063c1549fd1e8af2af405f6f309fb81.
This reverts commit 0acce0dc3c7ed0bbfdd21a164dd715e2090c98ad.
=> Allow building baremetal compiler-rt builtins without a sysroot

pycheribuild/projects/cross/apache.py
This probably has some rough edges that need to be fixed.
=> Add rules to build sslproc and an sslproc-enabled Apache.

pycheribuild/projects/disk_image.py, pycheribuild/projects/run_qemu.py, pycheribuild/qemu_utils.py
See #236 and https://github.com/CTSRD-CHERI/cheri-docker-images/pull/4 .  Many thanks to @jrtc27 for all the suggestions so far.
=> Better support for qcow2 disk images

README.md
An attempt to make it very clear how to use the cheribuild command based on comments from @rmn30
=> Rework the Basic usage section to be more explicit about ./

pycheribuild/projects/cross/openssl.py
Update Configure arguments to work with 1.1.1 and rework support for
multiple versions.
Move disabling parallel builds to the fett target where 1.0.2 is used
and has a broken Makefile.
Fix header install location for fett openssl.
This is a reimplementation of 25aa9947e4288cfa9801d42ef76ba182aa64a297
using tuples rather than the packaging version type.
=> openssl: enable non-fett build

pycheribuild/projects/cross/webkit.py, test-scripts/run_morello_webkit_tests.py
Fix webkit build for new versions of icu and add a test runner for sunspider benchmarks.
=> Add jsc tests

pycheribuild/projects/cross/gkermit.py
=> Add gkermit cross project

pycheribuild/projects/cross/cheribsd.py
I have a similar change to stop forcing OFED off, but CheriBSD isn't ready for that yet.
=> Trust src.opt.mk

pycheribuild/projects/cross/kde.py, pycheribuild/projects/cross/wayland.py
Instead of adding the libinput source directory as an include path, we can
create linux/{input,input-event-codes,uinput}.h headers that simply
#include the corresponding dev/evdev/ header.
The evdev-proto port downloads the Linux headers and patches those instead,
but it seems to me that creating a file that includes the native header is
less fragile as it doesn't rely on ioctl() numbers being compatible, etc.
According to https://bugreports.qt.io/browse/QTBUG-79130 and
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240964#c19 the evdev
headers sould not be used outside of the base system, but I'm not
convinced that using the Linux kernel definitions is any better?
=> Simplify handling of linux/input.h dependency

pycheribuild/projects/disk_image.py
These are rather like disk images, only without the filesystem,
partitions, or disks.  They are particularly useful as sources of NFS
exports for netbooted, diskless machines.
=> Add rootfs-tarball targets

Jenkinsfile, requirements.txt, tests/python-360.Dockerfile, tests/python-370.Dockerfile, tests/python-380.Dockerfile, tests/python-390.Dockerfile, tests/python-rc.Dockerfile, tests/requirements.txt, tests/ubuntu.Dockerfile
=> Install requirements.txt inside the docker images

pycheribuild/processutils.py
Otherwise we can end up blocking indefinitely in tcdrain().
Fixes: https://github.com/CTSRD-CHERI/cheribuild/issues/182
=> Only attempt to restore terminal attributes when in the foreground

pycheribuild/projects/cross/gdb.py
This should no longer be needed after updating to GDB12 and it appears to result in problems with newer macOS systems where moving binaries results
in errors: https://theevilbit.github.io/posts/amfi_launch_constraints/
=> Remove workaround for old GDB build system

pycheribuild/projects/cross/pkg.py
Ever since https://github.com/freebsd/pkg/pull/2024 landed
=> pkg builds out-of-tree now

README.md, pycheribuild/projects/build_qemu.py, pycheribuild/projects/repository.py
=> Check for mercurial installation and update README

pycheribuild/boot_cheribsd/__init__.py
Hopefully trivial, but just thought I'd do a PR to be sure
=> Restore boot_and_login default args
